name: 'Changelog File Generator'
description: 'Changelog File Generator Github Action'
author: 'Dan Petitt (Coderanger.com)'
branding:
  icon: 'clock'
  color: 'blue'

inputs:
  token:
    description: 'Github token'
    required: true
  release_version:
    description: 'Specify the current version to be released which matches the release/tag (normally with a `v` prefix)'
    required: true
  exclude:
    description: 'Exclude selected commit types (comma separated)'
    required: false
    default: ''
  file:
    description: 'Specify the path of a change log file for creating or updating; omit to not update any file'
    required: false
  files_to_commit:
    description: 'Specify which files you would like to automatically commit once changed (comma separated); this allows you to also commit any files with updated version numbers'
    required: false
    default: ''
  user:
    description: 'User email attributed to the committed files (default: actions@github.com)'
    required: false
    default: 'actions@github.com'
  userName:
    description: 'User name attributed to the committed files (default: Octokit Bot)'
    required: false
    default: 'Octokit Bot'
  branch:
    description: 'Specify which branch to commit files into (default: repos default-branch)'
    required: false

outputs:
  changelog:
    description: 'The generated changelogs'

runs:
  using: 'node12'
  main: 'action/index.js'
