name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      TAGREF: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all
      - run: |
          RELEASE=$(echo $TAGREF| cut -d'/' -f 3)
          echo ::set-output name=version::$RELEASE
        id: release_version

      - uses: danpetitt/changelog-file-generator@main
        id: changelog
        with:
          token: ${{ github.token }}
          file: 'CHANGELOG.md'
          exclude: chore,ci
          release_version: ${{ steps.release_version.outputs.version }}
          files_to_commit: 'CHANGELOG.md'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
