name: Test

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_version: v1.1.4

  test-with-exclude: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_version: v1.1.4
          exclude: 'chore,ci,build'

  test-generating-new-changelog-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all
      - run: |
          rm './CHANGELOG.md'
          CURRENT_DATE=$(date +%Y-%m-%d)
          echo ::set-output name=expected_heading::## \\[Release v1.1.4\\]\(https://github.com/danpetitt/changelog-file-generator/releases/tag/v1.1.4\) \($CURRENT_DATE\)
        id: heading_step
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: ./CHANGELOG.md
          release_version: v1.1.4
      - run: cat ./CHANGELOG.md
      - run: cat ./CHANGELOG.md | grep -q '# changelog-file-generator' ; echo $?
      - run: cat ./CHANGELOG.md | grep -q '${{ steps.heading_step.outputs.expected_heading }}' ; echo $?

  test-updating-existing-changelog-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all
      - run: |
          rm './CHANGELOG.md'
          printf '# ChangeLog for Auto Changelog Github Action\n\nSome sample text before we get to main release notes.\n\n' | tee './CHANGELOG.md'
          CURRENT_DATE=$(date +%Y-%m-%d)
          echo ::set-output name=expected_heading::## \\[Release v1.1.4\\]\(https://github.com/danpetitt/changelog-file-generator/releases/tag/v1.1.4\) \($CURRENT_DATE\)
        id: heading_step
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_version: v1.1.4
          file: ./CHANGELOG.md
      - run: cat ./CHANGELOG.md
      - run: cat ./CHANGELOG.md | grep -q '# ChangeLog for Auto Changelog Github Action' ; echo $?
      - run: cat ./CHANGELOG.md | grep -q 'Some sample text before we get to main release notes' ; echo $?
      - run: cat ./CHANGELOG.md | grep -q '${{ steps.heading_step.outputs.expected_heading }}' ; echo $?
