name: Test

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test-with-exclude: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: 'chore,ci,build'

  test-generating-new-changelog-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all
      - run: |
          CURRENT_DATE=$(date +%Y-%m-%d)
          echo ::set-output name=heading::## Release - $CURRENT_DATE
        id: heading_step
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: './CHANGELOG.md'
          title: '# ChangeLog for Auto Changelog Github Action'
          section: ${{ steps.heading_step.outputs.heading }}
      - run: cat ./CHANGELOG.md | grep -q '# ChangeLog for Auto Changelog Github Action' ; echo $?
      - run: cat ./CHANGELOG.md | grep -q '## Release - ' ; echo $?
      - run: cat ./CHANGELOG.md

  test-updating-existing-changelog-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all
      - run: printf '# ChangeLog for Auto Changelog Github Action\n\n' | tee ./CHANGELOG.md
      - run: |
          CURRENT_DATE=$(date +%Y-%m-%d)
          echo ::set-output name=heading::## Release - $CURRENT_DATE
        id: heading_step
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: './CHANGELOG.md'
          title: '# ChangeLog for Auto Changelog Github Action'
          section: ${{ steps.heading_step.outputs.heading }}
      - run: cat ./CHANGELOG.md | grep -q '# ChangeLog for Auto Changelog Github Action' ; echo $?
      - run: cat ./CHANGELOG.md | grep -q '## Release - ' ; echo $?
      - run: cat ./CHANGELOG.md
